// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcUlnAuz9DCDeUf4T6zgQ_Lr7GCWF1RM8',
    appId: '1:379107454883:web:686a810bf1aa241e8d3416',
    messagingSenderId: '379107454883',
    projectId: 'bh-finder-50ccf',
    authDomain: 'bh-finder-50ccf.firebaseapp.com',
    storageBucket: 'bh-finder-50ccf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg-xofOuPwN4ZSvD6T4B7X_T1rzT3dE0A',
    appId: '1:379107454883:android:2ac2e3aeff66e02d8d3416',
    messagingSenderId: '379107454883',
    projectId: 'bh-finder-50ccf',
    storageBucket: 'bh-finder-50ccf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADganqDAFFi3m1DCOOfIsEEsZ-QyCv-2g',
    appId: '1:379107454883:ios:2d19ee8f256b7eb68d3416',
    messagingSenderId: '379107454883',
    projectId: 'bh-finder-50ccf',
    storageBucket: 'bh-finder-50ccf.appspot.com',
    iosBundleId: 'com.example.bhFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADganqDAFFi3m1DCOOfIsEEsZ-QyCv-2g',
    appId: '1:379107454883:ios:2d19ee8f256b7eb68d3416',
    messagingSenderId: '379107454883',
    projectId: 'bh-finder-50ccf',
    storageBucket: 'bh-finder-50ccf.appspot.com',
    iosBundleId: 'com.example.bhFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcUlnAuz9DCDeUf4T6zgQ_Lr7GCWF1RM8',
    appId: '1:379107454883:web:4ff4e856dffa3c458d3416',
    messagingSenderId: '379107454883',
    projectId: 'bh-finder-50ccf',
    authDomain: 'bh-finder-50ccf.firebaseapp.com',
    storageBucket: 'bh-finder-50ccf.appspot.com',
  );

}